stages:
  - test
  - documentation
  - pages

test:
  stage: test
  image: registry.gitlab.com/everythingfunctional/dockerfpm
  script:
    - ./run_ci.sh

documentation:
  stage: documentation
  image: python:2.7
  script:
    - pip install ford
    - apt update && apt install -y graphviz
    - ford doc/front-matter.md
  artifacts:
    paths:
      - public

pages:
  stage: pages
  dependencies:
    - documentation
  script:
    - echo "Deploying to pages"
  artifacts:
    paths:
      - public
  only:
    - main
