name = "veggies"
version = "1.0.4"
license = "MIT"
author = "Brad Richardson"
maintainer = "everythingfunctional@protonmail.com"
copyright = "2020 Brad Richardson"

[dependencies]
iso_varying_string = { git = "https://gitlab.com/everythingfunctional/iso_varying_string.git", tag = "v4.0.0" }
strff = { git = "https://gitlab.com/everythingfunctional/strff.git", tag = "v3.1.0" }
